magazzino/urls.py
from django.conf.urls import patterns, url

from magazzino import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^classi/$', views.classedimateriale_index, name='classedimateriale_index'),
    url(r'^classi/(?P<cdm_sigla>[A-Z]+)', views.classedimateriale_detail, name='classedimateriale_detail'),
    url(r'^cerca/$', views.classedimateriale_search, name='classedimateriale_search'),
    url(r'^materiale-in-cassa/(?P<pk>\d+)/$', views.MaterialeInCassaDetailView.as_view(), name='materialeincassa-detail'),
    url(r'^materiale-in-cassa/(?P<pk>\d+)/edit$', views.MaterialeInCassaUpdate.as_view(), name='materialeincassa_update'),
)

nervia/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'nervia.views.home', name='home'),
    # url(r'^nervia/', include('nervia.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^magazzino/', include('magazzino.urls', namespace='magazzino')),
)

magazzino/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator

# Create your models here.


class Scavo(models.Model):
    '''Scavo archeologico.

    Corrisponde al campo DSC e alla relativa scheda di authority
    file.'''

    AREA_CHOICES = (
        ('TEATR', 'Teatro'),
        ('TERME', 'Terme'),
        ('GAS', 'Gas'),
        ('CAVAL', 'Cavalcavia'),
        ('NECRO', 'Necropoli'),
        ('VALTA', 'Ventimiglia alta'),
        ('EXTRA', 'Scavi extraurbani'),
        )

    area = models.CharField(max_length=5, choices=AREA_CHOICES)
    settore = models.CharField(max_length=50)
    scan = models.CharField('SCAN',
                            help_text='''
Denominazione dello scavo. Es.“Albintimilium, teatro, parodos est”.
Seguire sempre l'ordine dal generale al particolare.''',
                            max_length=45,
                            unique=True)
    scad = models.TextField('SCAD',
                            help_text='Descrizione')
    luogo = models.CharField('Località', max_length=100)
    dsch = models.CharField('DSCH',
                            help_text='Sigla identificativa. Es. “VGF”, “XXSP”',
                            max_length=8,
                            blank=True)

    def __unicode__(self):
        return self.scan

    class Meta:
        verbose_name_plural = "scavi"


class ContestoScavo(models.Model):
    '''Unità stratigrafica, strato, livello o altro.

    Un qualunque tipo di indicazione sulla provenienza del materiale
    di scavo, in forma sintetica.'''

    scavo = models.ForeignKey(Scavo)
    numero_nome = models.CharField('Numero o nome',
                                   help_text='Es. “US 551”, “Strato II, parodos est, 3° taglio”.',
                                   max_length=50)

    def __unicode__(self):
        return "%s - %s" % (self.scavo, self.numero_nome)

    class Meta:
        verbose_name_plural = "contesti di scavo"


class Vano(models.Model):
    '''Un vano all'interno di un magazzino.'''

    ENEL = 'ENEL'
    GAS = 'GAS'
    ANTIQUARIUM = 'ANTIQ'

    MAGAZZINO_CHOICES = (
        (ENEL, 'Magazzino ENEL'),
        (GAS, 'Magazzino Gas'),
        (ANTIQUARIUM, 'Magazzino Antiquarium'),
        )

    numero = models.IntegerField('Numero del vano')
    magazzino = models.CharField(max_length=5, choices=MAGAZZINO_CHOICES)
    desc = models.TextField('Descrizione')

    def __unicode__(self):
        return u'%s - Vano %d' % (self.get_magazzino_display(), self.numero)

    class Meta:
        verbose_name_plural = 'vani'


class CassaManager(models.Manager):
    def get_by_natural_key(self, magazzino, numero):
        return self.get(ldcn__magazzino=magazzino, number=numero)


class Cassa(models.Model):
    '''Basata sul modello "Scheda di cassa".

    Fa riferimento alla scheda ICCD TMA (Tabella materiali).'''

    # informazioni di base
    number = models.CharField('Numero di cassa', max_length=50)
    numscavo = models.IntegerField(
        'Numero di cassa dello scavo',
        blank=True,
        null=True,
        help_text='Il numero di cassa nella numerazione dello scavo, se presente')

    # CD - Codici
    tsk = models.CharField('TSK',
                           help_text='Tipo scheda',
                           max_length=4,
                           default='TMA',
                           editable=False)
    LIR_CHOICES = (
        ('I', 'Inventario'),
        ('P', 'Precatalogo'),
        ('C', 'Catalogo'),
        )
    lir = models.CharField('LIR',
                           help_text='Livello ricerca',
                           max_length=5,
                           choices=LIR_CHOICES,
                           default='I')
    ## NCT - Codice univoco
    NCTR_CODICI = (
        # codici ICCD
        ('01', 'Piemonte'),
        ('02', "Valle d'Aosta"),
        ('03', 'Lombardia'),
        ('04', 'Trentino-Alto Adige'),
        ('05', 'Veneto'),
        ('06', 'Friuli-Venezia Giulia'),
        ('07', 'Liguria'),
        ('08', 'Emilia-Romagna'),
        ('09', 'Toscana'),
        ('10', 'Umbria'),
        ('11', 'Marche'),
        ('12', 'Lazio'),
        ('13', 'Abruzzo'),
        ('14', 'Molise'),
        ('15', 'Campania'),
        ('16', 'Puglia'),
        ('17', 'Basilicata'),
        ('18', 'Calabria'),
        ('19', 'Sicilia'),
        ('20', 'Sardegna'),
        )
    nctr = models.CharField('NCTR',
                            help_text='Codice regione',
                            max_length=2,
                            choices=NCTR_CODICI,
                            default='07')
    nctn = models.CharField('NCTN',
                            help_text='Numero catalogo generale',
                            max_length=8,
                            unique=True,
                            validators=[RegexValidator('[0-9]'*8)],
                            default='00000000')
    esc = models.CharField('ESC',
                           help_text='Ente schedatore',
                           max_length=25,
                           default='S19')
    ecp = models.CharField('ECP',
                           help_text='Ente competente',
                           max_length=25,
                           default='S19')

    # OG - Oggetto
    ## OGT - Oggetto
    ### OGTD = materiale proveniente da Unità Stratigrafica
    ### OGTM - Definizione materiale componente = ceramica/vetro...

    # RE - Modalità di reperimento
    ## DSC - Dati di scavo
    dscd = models.CharField('DSCD',
                            help_text='''
Data in cui è stato effettuato l’intervento di scavo archeologico,
nel formato AAAA/MM/GG. Esempi: 2002/03/25, 2004/00/00, 2005/07/21-2005/10/12.''',
                            max_length=50,
                            validators=[RegexValidator('[0-9][0-9][0-9][0-9]/[0-1][0-9]/[0-3][0-9]')])

    # LC - Localizzazione geografico-amministrativa
    ## PVC LOCALIZZAZIONE GEOGRAFICO-AMMINISTRATIVA ATTUALE
    pvcs = models.CharField('PVCS', help_text='Stato', max_length=50, default='Italia')
    pvcr = models.CharField('PVCR', help_text='Regione', max_length=25, default='Liguria')
    pvcp = models.CharField('PVCP', help_text='Provincia', max_length=3, default='IM')
    pvcc = models.CharField('PVCC', help_text='Comune', max_length=50, default='Ventimiglia')

    # LDC - Collocazione specifica
    ldct = models.CharField('LDCT',
                            help_text='Tipologia del contenitore',
                            max_length=25,
                            default='magazzino')
    ldcn = models.ForeignKey(Vano,
                             verbose_name='LDCN',
                             help_text='Magazzino e vano')
    ldcs = models.CharField('LDCS',
                            help_text='Specifiche: corridoio, colonna',
                            max_length=50)

    # DT CRONOLOGIA
    ## DTZ CRONOLOGIA GENERICA
    dtzg = models.CharField('DTZG',
                            help_text='Fascia cronologica di riferimento',
                            max_length=50)

    DTM_CHOICES = ((c, c) for c in
        (
            'analisi dei materiali',
            'analisi chimico-fisica',
            'analisi stilistica',
            'bibliografia',
            'bollo',
            'contesto',
            'data',
            'dati epigrafici',
            'documentazione',
            'tradizione orale',
            'NR (recupero pregresso)'
            ))

    dtm = models.CharField('DTM',
                           help_text='Motivazione cronologia',
                           max_length=250,
                           choices=DTM_CHOICES)

    # MA MATERIALE
    ## MAC MATERIALE COMPONENTE
    macc = models.CharField('MACC',
                            help_text='Categoria: es. ceramica oppure ceramica/vetro/metallo',
                            max_length=100)
    macq = models.CharField('MACQ', help_text='Quantità', max_length=100)

    # TU CONDIZIONE GIURIDICA E VINCOLI
    ## CDG CONDIZIONE GIURIDICA
    cdgg = models.CharField('CDGG',
                            help_text='Condizione giuridica - Indicazione generica',
                            max_length=50,
                            default='proprietà Stato')

    # AD ACCESSO AI DATI
    ## ADS SPECIFICHE DI ACCESSO AI DATI
    ADSP_CHOICES = (
        ('1', 'intera scheda visibile'),
        ('2', 'limitazione per privacy e tutela')
        )
    adsp = models.CharField('ADSP',
                            help_text='Profilo di accesso',
                            max_length=1,
                            choices=ADSP_CHOICES,
                            default='1')
    adsm = models.CharField('ADSM',
                            help_text='Motivazione',
                            max_length=70,
                            default='dati liberamente accessibili')

    # FTA DOCUMENTAZIONE FOTOGRAFICA
    ftax = models.CharField('FTAX', help_text='genere', max_length=50)
    ftad = models.CharField('FTAD', help_text='data', max_length=25)
    ftat = models.TextField('FTAT', help_text='note', max_length=250)

    # DRA DOCUMENTAZIONE GRAFICA
    drax = models.CharField('DRAX', help_text='genere', max_length=25)
    drat = models.CharField('DRAT', help_text='tipo', max_length=50)
    drao = models.TextField('DRAO', help_text='note', max_length=250)
    dras = models.CharField('DRAS', help_text='scala', max_length=25)
    drac = models.CharField('DRAC', help_text='collocazione', max_length=50)
    draa = models.CharField('DRAA', help_text='autore', max_length=50)
    drad = models.CharField('DRAD', help_text='data', max_length=25)

    # CM COMPILAZIONE
    ## CMP COMPILAZIONE
    cmpd = models.DateField('CMPD', help_text='Data')
    cmpn = models.CharField('CMPN', help_text='Nome', max_length=70)
    fur = models.CharField('FUR', help_text='Funzionario responsabile', max_length=70)

    objects = CassaManager()

magazzino/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from magazzino.models import Cassa, ClasseDiMateriale, ContestoScavo, MaterialeInCassa

def index(request):
    return render(request, 'magazzino/index.html')

def classedimateriale_index(request):
    cdm = ClasseDiMateriale.objects.all()
    return render(request, 'magazzino/classedimateriale_list.html', {'cdm': cdm})

def classedimateriale_detail(request, cdm_sigla):
    cdm = get_object_or_404(ClasseDiMateriale, sigla=cdm_sigla)
    return render(request, 'magazzino/classedimateriale_detail.html', {'cdm': cdm})

def classedimateriale_search(request):
    '''Search based on exact match for ClasseDiMateriale `classe` or `sigla`'''

    res = ClasseDiMateriale.objects.filter(classe__icontains=request.GET['search_string'])
    return render(request, 'magazzino/classedimateriale_searchresults.html', {'cdm': res, 'ss': request.GET['search_string']})


class MaterialeInCassaDetailView(DetailView):

    model = MaterialeInCassa

    def get_context_data(self, **kwargs):
        context = super(MaterialeInCassaDetailView, self).get_context_data(**kwargs)
        context['mic'] = context['materialeincassa']
        return context

class MaterialeInCassaUpdate(UpdateView):
    model = MaterialeInCassa

magazzino/templates/magazzino/base_generic.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Scheda di cassa</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'magazzino/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'magazzino/css/navbar-fixed-top.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'magazzino/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

        <!-- Fixed navbar -->
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'magazzino:index' %}">Scheda di cassa</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'magazzino:index' %}">Home</a></li>
                <li class="active"><a href="{% url 'magazzino:classedimateriale_index' %}">Classi</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li>
                    <form role="form" action="{% url 'magazzino:classedimateriale_search' %}" method="get" class="navbar-form navbar-right">
                    {% csrf_token %}
                    <input type="text" placeholder="Ricerca classi" name="search_string" class="form-control" />
                    </form>
                </li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>

        <div class="container">
            {% block content %}
            {% endblock %}

        </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'magazzino/js/jquery/1.11.1/jquery.min.js' %}"></script>
    <script src="{% static 'magazzino/js/docs.min.js' %}"></script>
    <script src="{% static 'magazzino/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'magazzino/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

magazzino/templates/magazzino/classedimateriale_base.html
{% extends "magazzino/base_generic.html" %}

{% block content %}
{% endblock %}

magazzino/templates/magazzino/classedimateriale_detail.html
{% extends "magazzino/classedimateriale_base.html" %}

{% block content %}

<h1>{{ cdm.sigla }} ‒ {{ cdm.classe }}</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Cassa<th>Contesto<th>Forma<th>Tipologia<th>Numero frammenti
        </tr>
    </thead>
    <tbody>
    {% for mic in cdm.materialeincassa_set.all %}
        <tr>
            <td>{{ mic.cassa.number }}
            <td>{{ mic.contesto }}
            <td>{{ mic.macd }}
            <td>{{ mic.macp }}
            <td class="align-right">{{ mic.orli|add:mic.anse|add:mic.pareti|add:mic.fondi|add:mic.piedi }}
            <td class="align-right"><a href="{% url 'magazzino:materialeincassa-detail' mic.pk %}">dettaglio</a>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

magazzino/templates/magazzino/classedimateriale_list.html
{% extends "magazzino/classedimateriale_base.html" %}

{% block content %}
<h1>Classi di materiale</h1>

{% regroup cdm|dictsort:'famiglia' by famiglia as cdm_list %}

{% for fam in cdm_list %}
<h2>{{ fam.grouper }}</h2>
<ul>
{% for item in fam.list %}
    <li><a href="{% url 'magazzino:classedimateriale_detail' item.sigla %}">{{ item.sigla }}</a> ‒ {{ item.classe }}
{% endfor %}
</ul>
{% endfor %}
{% endblock %}

magazzino/templates/magazzino/classedimateriale_searchresults.html
{% extends "magazzino/classedimateriale_base.html" %}

{% block content %}

<h1>Classi di materiale</h1>

<p>Classi contenenti <i>{{ ss }}</i>.

{% regroup cdm|dictsort:'famiglia' by famiglia as cdm_list %}

{% for fam in cdm_list %}
<h2>{{ fam.grouper }}</h2>
<ul>
{% for item in fam.list %}
    <li><a href="{% url 'magazzino:classedimateriale_detail' item.sigla %}">{{ item.sigla }}</a> ‒ {{ item.classe }} <i>({{ item.materialeincassa_set.count }})</i>
{% endfor %}
</ul>
{% endfor %}
{% endblock %}

magazzino/templates/magazzino/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Scheda di cassa</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'magazzino/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'magazzino/css/cover.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'magazzino/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Albintimilium</h3>
              <ul class="nav masthead-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="/magazzino/classi">Classi</a></li>
              </ul>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Scheda di cassa</h1>
            <p class="lead">Compilazione e ricerca scheda TMA</p>
            <p class="lead">
                <form role="form" action="{% url 'magazzino:classedimateriale_search' %}" method="get">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" placeholder="Digitare qui" name="search_string" class="form-control" />
                </div>
                <input type="submit" value="Cerca" class="btn btn-lg btn-default" />
                </form>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'magazzino/js/jquery/1.11.1/jquery.min.js' %}"></script>
    <script src="{% static 'magazzino/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'magazzino/js/docs.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'magazzino/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

magazzino/templates/magazzino/materialeincassa_detail.html
{% extends "magazzino/base_generic.html" %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <h1>Dettaglio materiale</h1>

        <table class="table table-striped">
            <tr><th>Contesto<td>{{ mic.contesto }}
            <tr><th>Cassa<td>{{ mic.cassa }}
            <tr><th>Classe<td><a href="{% url 'magazzino:classedimateriale_detail' mic.macl.sigla %}">{{ mic.macl }}</a>
            <tr><th>Forma<td><a href="#">{{ mic.macd }}</a>
            {% if mic.macp %}
            <tr><th>Tipologia<td>{{ mic.macp }}
            {% endif %}
            {% if mic.macn %}
            <tr><th>Osservazioni<td>{{ mic.macn }}
            {% endif %}
        </table>
    </div>
    <div class="col-md-6">
        <h2>Numero frammenti</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>&nbsp;<th>Quantità<th>Numeri di inventario
                </tr>
            </thead>
            <tbody>
                {% if mic.orli %}<tr><th>Orli<td class="text-right">{{ mic.orli }}<td>{{ mic.numeri_inventario_orli }}{% endif %}
                {% if mic.anse %}<tr><th>Anse<td class="text-right">{{ mic.anse }}<td>{{ mic.numeri_inventario_anse }}{% endif %}
                {% if mic.pareti %}<tr><th>Pareti<td class="text-right">{{ mic.pareti }}<td>{{ mic.numeri_inventario_pareti }}{% endif %}
                {% if mic.fondi %}<tr><th>Fondi<td class="text-right">{{ mic.fondi }}<td>{{ mic.numeri_inventario_fondi }}{% endif %}
                {% if mic.piedi %}<tr><th>Piedi<td class="text-right">{{ mic.piedi }}<td>{{ mic.numeri_inventario_piedi }}{% endif %}
            </tbody>
            <tfooter>
                <tr><th>Totale<td class="text-right">{{ mic.orli|add:mic.anse|add:mic.pareti|add:mic.fondi|add:mic.piedi }}<td>&nbsp;
            </tfooter>
        </table>
    </div>
</div>
{% endblock %}

magazzino/templates/magazzino/materialeincassa_form.html
{% extends "magazzino/base_generic.html" %}

{% block content %}
<form action="{% url 'magazzino:materialeincassa_update' object.id %}" method="post" role="form">
{% csrf_token %}
{{ form }}
<input type="submit" />
</form>
{% endblock %}